function customRender(ReactElement,MainCondainer){   // here initialize that what is custome render
    const domElement = document.createElement(ReactElement.type)
    domElement.innerHTML = ReactElement.children;
    /*domElement.setAttribute('href', ReactElement.props.href) /// these step not cool so use new way
    domElement.setAttribute('target',ReactElement.props.target)
    */
   for(const prop in ReactElement.props){
    //if(prop === 'children') continue;
    domElement.setAttribute(prop , ReactElement.props[prop])

   }
    MainCondainer.appendChild(domElement)
}

const ReactElement = {          /// 2.componet function achully view by react like this
    type : 'a',                                /// this process achullay known as parsing
    props : {                               // React element generated by bundiler babler
        href : "https://google.com",
        target: "_blank"
    },
    children : 'click me to vist google'
}
const MainContainer = document.querySelector('#root') //1. adding to dom of browser 

customRender(ReactElement , MainContainer) // 3. here create a method Custome render to inject ReactElement to MainCondainer
                                           
